# Generated by Django 3.2.5 on 2021-07-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210720_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valuealert',
            name='crypto',
        ),
        migrations.RemoveField(
            model_name='valuealert',
            name='currency',
        ),
        migrations.AddField(
            model_name='alert',
            name='crypto',
            field=models.CharField(default='BTC', max_length=3),
        ),
        migrations.AddField(
            model_name='alert',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
